### ISSUE TITLE
一些代码实现问题

### ISSUE THREAD

**Issue by Alexwong-1024** [iwanglei1/NIRATSpecNet#1]
我想知道您在tensorflow框架下是如何使用Gard-CAM对模型进行解释性功能的实现的，期待您的回复

**Comment by iwanglei1** [comment]
使用Gard-CAM解释这部分是用的Keras这个高层API的gard-cam方法   那个Notebook中要是没有的话那就是丢失了。 
到CSDN上随便搜一个gard-cam以及图像热点的关键词即可。这里面有个小坑，就是光谱数据是一维数据，需要对那个cam方法进行一个简单的修改   适应一维数据即可  。 默认画出来的图应该是长条状的  贡献度高的地方会显示亮蓝色
